# Part I

In [1]:
import pandas as pd
import numpy as np
import random
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/Rising-Stars-by-Sunshine/stats201-prediction-josh/main/data/phlgdp1.csv')
df.head()

   Year       GDP
0  1960  0.000000
1  1961  5.695471
2  1962  4.846294
3  1963  7.016265
4  1964  3.402494

In [3]:
df.columns

Index(['Year', 'GDP'], dtype='object')

In [4]:
df.dtypes

Year      int64
GDP     float64
dtype: object

# Part II

## 2.1.

In [5]:
df['GDPchange'] = df['GDP'].pct_change(1)
df.head()

   Year       GDP  GDPchange
0  1960  0.000000        NaN
1  1961  5.695471        inf
2  1962  4.846294  -0.149097
3  1963  7.016265   0.447759
4  1964  3.402494  -0.515056

# Part III:

In [ ]:
#@title Define the Congestion Threshold
cut = 0 #@param {type:"number"}

## 3.1. Method 1: If function

In [18]:
df['Positive'] = df['GDP'].pct_change(1)
df.head(5)

   Year       GDP  GDPchange  Positive
0  1960  0.000000        NaN       NaN
1  1961  5.695471        inf       inf
2  1962  4.846294  -0.149097 -0.149097
3  1963  7.016265   0.447759  0.447759
4  1964  3.402494  -0.515056 -0.515056

In [12]:
cut=0

In [17]:
df['Positive'] = df['GDP'].apply(lambda x: 1 if x>= cut else 0)
df.head(5)

   Year       GDP  GDPchange  Positive
0  1960  0.000000        NaN         1
1  1961  5.695471        inf         1
2  1962  4.846294  -0.149097         1
3  1963  7.016265   0.447759         1
4  1964  3.402494  -0.515056         1

In [19]:
df['Positive'] = df['GDP'].apply(lambda x: 1 if x>= cut else 0)
df.head(5)

   Year       GDP  GDPchange  Positive
0  1960  0.000000        NaN         1
1  1961  5.695471        inf         1
2  1962  4.846294  -0.149097         1
3  1963  7.016265   0.447759         1
4  1964  3.402494  -0.515056         1

# Part 4

In [23]:
window=10

In [26]:
df['GDPpast'] =df['GDP'].shift(1)
df.head(5)

   Year       GDP  GDPchange  Positive  GDP_past   GDPma10   GDPpast
0  1960  0.000000        NaN         1       NaN       NaN       NaN
1  1961  5.695471        inf         1  0.000000  0.000000  0.000000
2  1962  4.846294  -0.149097         1  5.695471  2.847735  5.695471
3  1963  7.016265   0.447759         1  4.846294  3.513922  4.846294
4  1964  3.402494  -0.515056         1  7.016265  4.389508  7.016265

In [28]:
df['GDPma10']=df['GDP_past'].rolling(window=window,min_periods=1).mean()
df.head(5)

   Year       GDP  GDPchange  Positive  GDP_past   GDPma10   GDPpast
0  1960  0.000000        NaN         1       NaN       NaN       NaN
1  1961  5.695471        inf         1  0.000000  0.000000  0.000000
2  1962  4.846294  -0.149097         1  5.695471  2.847735  5.695471
3  1963  7.016265   0.447759         1  4.846294  3.513922  4.846294
4  1964  3.402494  -0.515056         1  7.016265  4.389508  7.016265

# Part V Train and Test Split

In [29]:
from sklearn.model_selection import TimeSeriesSplit
tss = TimeSeriesSplit()
print(tss)

TimeSeriesSplit(gap=0, max_train_size=None, n_splits=5, test_size=None)

In [30]:
# change the train and test split parameters 
tss = TimeSeriesSplit(gap=0, max_train_size=None, n_splits=2, test_size=None)

In [31]:
for train_idx, test_idx in tss.split(df):
    print("TRAIN:", train_idx, "TEST:", test_idx)

TRAIN: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21] TEST: [22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41]
TRAIN: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41] TEST: [42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61]

In [32]:
train_idx

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41])

In [33]:
test_idx

array([42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
       59, 60, 61])

In [34]:
train_df = df.filter(items=train_idx, axis=0)
test_df =  df.filter(items=test_idx, axis=0)

In [35]:
train_df.head()

   Year       GDP  GDPchange  Positive  GDP_past   GDPma10   GDPpast
0  1960  0.000000        NaN         1       NaN       NaN       NaN
1  1961  5.695471        inf         1  0.000000  0.000000  0.000000
2  1962  4.846294  -0.149097         1  5.695471  2.847735  5.695471
3  1963  7.016265   0.447759         1  4.846294  3.513922  4.846294
4  1964  3.402494  -0.515056         1  7.016265  4.389508  7.016265

In [36]:
test_df.head()

    Year       GDP  GDPchange  Positive  GDP_past   GDPma10   GDPpast
42  2002  3.716255   0.218751         1  3.049232  3.290927  3.049232
43  2003  5.086911   0.368827         1  3.716255  3.620789  3.716255
44  2004  6.569229   0.291398         1  5.086911  3.911291  5.086911
45  2005  4.942505  -0.247628         1  6.569229  4.130848  6.569229
46  2006  5.316417   0.075652         1  4.942505  4.162576  4.942505

# Part VI Prepare the Train and Test Data for Classification and Regression

## 6.1. Classification

### 6.1.1 Define the columns (Y, X) for Classification

In [38]:
cols_C = ['Positive','GDPchange']

### 6.1.2 Define the Data Frame of Train and Test Data for Classification

In [39]:
df_C_train = train_df[cols_C]
df_C_test = test_df[cols_C]

### 6.1.3 Export the Train and Test Data for Classification

In [40]:
df_C_train.head()

   Positive  GDPchange
0         1        NaN
1         1        inf
2         1  -0.149097
3         1   0.447759
4         1  -0.515056

In [41]:
df_C_train.to_csv('Classification_Train.csv')

In [42]:
df_C_test.head()

    Positive  GDPchange
42         1   0.218751
43         1   0.368827
44         1   0.291398
45         1  -0.247628
46         1   0.075652

In [43]:
df_C_test.to_csv('Classification_Test.csv')

## 6.2 Regression

### 6.2.1. Define the columns (Y, X) for Regression

In [44]:
cols_R = ['GDPchange','GDPpast']

### 6.2.2. Define the Data Frame of Train and Test Data for Regression

In [45]:
df_R_train = train_df[cols_R]
df_R_test = test_df[cols_R]

### 6.2.3. Export the Train and Test Data for Regression

In [46]:
df_R_train.head()

   GDPchange   GDPpast
0        NaN       NaN
1        inf  0.000000
2  -0.149097  5.695471
3   0.447759  4.846294
4  -0.515056  7.016265

In [47]:
df_R_train.to_csv('Regression_Train.csv')

In [48]:
df_R_test.head()

    GDPchange   GDPpast
42   0.218751  3.049232
43   0.368827  3.716255
44   0.291398  5.086911
45  -0.247628  6.569229
46   0.075652  4.942505

In [49]:
df_R_test.to_csv('Regression_Test.csv')

In [50]:
from google.colab import files
files.download("Regression_Test.csv")

In [51]:
from google.colab import files
files.download("Regression_Train.csv")

In [52]:
from google.colab import files
files.download("Classification_Test.csv")

In [54]:
from google.colab import files
files.download("Classification_Train.csv")

FileNotFoundError: ignored